name: Build and Deploy to Blob-Builds

on:
  push:
    branches:
      - Experimental/1.21.x
  workflow_dispatch:


jobs:
  blob-build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21

      - name: Build with Maven
        run: mvn package

      - name: Upload to Blob Builds
        uses: WalshyDev/blob-builds/gh-action@main
        with:
          project: RelicsOfCthonia
          apiToken: ${{ secrets.BLOB_BUILDS_API_TOKEN }}
          releaseNotes: ${{ github.event.head_commit.message }}
