name: Build with Maven and Do Runtime Test

on:
  workflow_dispatch:
  push:
    branches:
      - Experimental/1.21.x
  pull_request:
    branches:
      - Experimental/1.21.x
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2.3.3
      
    - name: Set up JDK 21
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 21
        
    - name: Maven Build
      run: mvn clean package --file pom.xml
      
    - name: Upload the artifact
      uses: actions/upload-artifact@v4
      with:
        name: artifact-${{ github.event.number }}
        path: 'target/RelicsOfCthonia*.jar'
  
  runtime-test:
    name: Plugin Runtime Test 
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - mcVersion: '1.20.6'
            javaVersion: '21'
          - mcVersion: '1.21.4'
            javaVersion: '21'    
    
    steps:        
      - uses: FN-FAL113/minecraft-plugin-runtime-test@v1.1.7
        with:
          server-version: ${{ matrix.mcVersion }}
          java-version: ${{ matrix.javaVersion }}
          artifact-name: artifact-${{ github.event.number }}
